const currencies = [
{"locale":"ps-AF","text":"Afghan Afghani","code":"AFN","exchange":"2"},
{"locale":"sv-AX","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"sq-AL","text":"Albanian Lek","code":"ALL","exchange":"2"},
{"locale":"ar-DZ","text":"Algerian Dinar","code":"DZD","exchange":"2"},
{"locale":"en-AS","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"ca-AD","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"ln-AO","text":"Angolan Kwanza","code":"AOA","exchange":"2.5"},
{"locale":"en-AI","text":"East Caribbean Dollar","code":"XCD","exchange":".5"},
{"locale":"en-AG","text":"East Caribbean Dollar","code":"XCD","exchange":".5"},
{"locale":"es-AR","text":"Argentine Peso","code":"ARS","exchange":"2"},
{"locale":"hy-AM","text":"Armenian Dram","code":"AMD","exchange":"2.5"},
{"locale":"es-AW","text":"Aruban Florin","code":"AWG","exchange":"0"},
{"locale":"en-AU","text":"Australian Dollar","code":"AUD","exchange":"0"},
{"locale":"de-AT","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"az-AZ","text":"Azerbaijani Manat","code":"AZN","exchange":"0"},
{"locale":"en-BS","text":"Bahamian Dollar","code":"BSD","exchange":"0"},
{"locale":"ar-BH","text":"Bahraini Dinar","code":"BHD","exchange":"-.5"},
{"locale":"bn-BD","text":"Bangladeshi Taka","code":"BDT","exchange":"2"},
{"locale":"en-BB","text":"Bajan Dollar","code":"BBD","exchange":"0"},
{"locale":"be-BY","text":"Belarusian Ruble","code":"BYN","exchange":"0"},
{"locale":"en-BE","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"en-BZ","text":"Belizean Dollar","code":"BZD","exchange":"0"},
{"locale":"yo-BJ","text":"CFA Franc","code":"XOF","exchange":"2.5"},
{"locale":"en-BM","text":"Bermudan Dollar","code":"BMD","exchange":"0"},
{"locale":"dz-BT","text":"Bhutanese Ngultrum","code":"BTN","exchange":"2"},
{"locale":"qu-BO","text":"Bolivian Boliviano","code":"BOB","exchange":"1"},
{"locale":"nl-BQ","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"bs-BA","text":"Bosnia-Herzegovina Convertible Mark","code":"BAM","exchange":"0"},
{"locale":"tn-BW","text":"Botswanan Pula","code":"BWP","exchange":"1"},
{"locale":"pt-BR","text":"Brazilian Real","code":"BRL","exchange":".5"},
{"locale":"en-IO","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"ms-BN","text":"Brunei Dollar","code":"BND","exchange":"0"},
{"locale":"bg-BG","text":"Bulgarian Lev","code":"BGN","exchange":"0"},
{"locale":"ff-BF","text":"CFA Franc","code":"XOF","exchange":"2.5"},
{"locale":"rn-BI","text":"Burundi Franc","code":"BIF","exchange":"3"},
{"locale":"kea-CV","text":"Cabo Verdean Escudo","code":"CVE","exchange":"2"},
{"locale":"km-KH","text":"Cambodian Riel","code":"KHR","exchange":"3.5"},
{"locale":"en-CM","text":"CFA Franc","code":"XAF","exchange":"2.5"},
{"locale":"en-CA","text":"Canadian Dollar","code":"CAD","exchange":"0"},
{"locale":"en-KY","text":"Cayman Islands Dollar","code":"KYD","exchange":"0"},
{"locale":"ln-CF","text":"CFA Franc","code":"XAF","exchange":"2.5"},
{"locale":"fr-TD","text":"CFA Franc","code":"XAF","exchange":"2.5"},
{"locale":"es-CL","text":"Chilean Peso","code":"CLP","exchange":"3"},
{"locale":"zh-CN","text":"Chinese Yuan Renminbi","code":"CNY","exchange":"1"},
{"locale":"en-CX","text":"Australian Dollar","code":"AUD","exchange":"0"},
{"locale":"en-CC","text":"Australian Dollar","code":"AUD","exchange":"0"},
{"locale":"es-CO","text":"Colombian Peso","code":"COP","exchange":"3.5"},
{"locale":"ar-KM","text":"Comorian Franc ","code":"KMF","exchange":"2.5"},
{"locale":"ln-CD","text":"Congolese Franc","code":"CDF","exchange":"3"},
{"locale":"ln-CG","text":"CFA Franc","code":"XAF","exchange":"2.5"},
{"locale":"en-CK","text":"New Zealand Dollar","code":"NZD","exchange":"0"},
{"locale":"es-CR","text":"Costa Rican Colón","code":"CRC","exchange":"2.5"},
{"locale":"fr-CI","text":"CFA Franc","code":"XOF","exchange":"2.5"},
{"locale":"hr-HR","text":"Croatian Kuna","code":"HRK","exchange":"1"},
{"locale":"es-CU","text":"Cuban Peso","code":"CUP","exchange":"1"},
{"locale":"nl-CW","text":"Netherlands Antillean Guilder","code":"ANG","exchange":"0"},
{"locale":"el-CY","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"cs-CZ","text":"Czech Koruna","code":"CZK","exchange":"1"},
{"locale":"da-DK","text":"Danish Krone","code":"DKK","exchange":"1"},
{"locale":"ar-DJ","text":"Djibouti Franc","code":"DJF","exchange":"2"},
{"locale":"en-DM","text":"East Caribbean Dollar","code":"XCD","exchange":".5"},
{"locale":"es-DO","text":"Dominican Peso","code":"DOP","exchange":"1.5"},
{"locale":"es-EC","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"ar-EG","text":"Egyptian Pound","code":"EGP","exchange":"1"},
{"locale":"es-SV","text":"Salvadoran Colón","code":"SVC","exchange":"1"},
{"locale":"es-GQ","text":"CFA Franc","code":"XAF","exchange":"2.5"},
{"locale":"ti-ER","text":"Eritrean Nakfa","code":"ERN","exchange":"1"},
{"locale":"et-EE","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"ss-SZ","text":"Swazi Lilangeni","code":"SZL","exchange":"1"},
{"locale":"am-ET","text":"Ethiopian Birr","code":"ETB","exchange":"1.5"},
{"locale":"en-FK","text":"Falkland Islands Pound","code":"FKP","exchange":"0"},
{"locale":"fo-FO","text":"Danish Krone","code":"DKK","exchange":"1"},
{"locale":"en-FJ","text":"Fiji Dollar","code":"FJD","exchange":"0"},
{"locale":"fi-FI","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"co-FR","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"fr-GF","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"fr-PF","text":"CFP Franc","code":"XPF","exchange":"2"},
{"locale":"fr-GA","text":"CFA Franc","code":"XAF","exchange":"2.5"},
{"locale":"ff-GM","text":"Gambian Dalasi","code":"GMD","exchange":"1.5"},
{"locale":"ka-GE","text":"Georgian Lari","code":"GEL","exchange":".5"},
{"locale":"dsb-DE","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"gaa-GH","text":"Ghanaian Cedi","code":"GHS","exchange":".5"},
{"locale":"en-GI","text":"Gibraltar Pound","code":"GIP","exchange":"0"},
{"locale":"el-GR","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"kl-GL","text":"Danish Krone","code":"DKK","exchange":"1"},
{"locale":"en-GD","text":"East Caribbean Dollar","code":"XCD","exchange":".5"},
{"locale":"fr-GP","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"en-GU","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"es-GT","text":"Guatemalan Quetzal","code":"GTQ","exchange":"1"},
{"locale":"en-GG","text":"Pound Sterling","code":"GBP","exchange":"0"},
{"locale":"nqo-GN","text":"Guinean Franc","code":"GNF","exchange":"4"},
{"locale":"ff-GW","text":"CFA Franc","code":"XOF","exchange":"2.5"},
{"locale":"es-GY","text":"Guyanese Dollar","code":"GYD","exchange":"2"},
{"locale":"fr-HT","text":"Haitian Gourde","code":"HTG","exchange":"2"},
{"locale":"la-VA","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"es-HN","text":"Honduran Lempira","code":"HNL","exchange":"1"},
{"locale":"yue-HK","text":"Hong Kong Dollar","code":"HKD","exchange":"1"},
{"locale":"hu-HU","text":"Hungarian Forint","code":"HUF","exchange":"2.5"},
{"locale":"is-IS","text":"Icelandic Króna","code":"ISK","exchange":"2"},
{"locale":"sa-IN","text":"Indian Rupee","code":"INR","exchange":"2"},
{"locale":"id-ID","text":"Indonesian Rupiah","code":"IDR","exchange":"4"},
{"locale":"fa-IR","text":"Iranian Rial","code":"IRR","exchange":"4.5"},
{"locale":"ar-IQ","text":"Iraqi Dinar","code":"IQD","exchange":"3"},
{"locale":"ga-IE","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"gv-IM","text":"Pound Sterling","code":"GBP","exchange":"0"},
{"locale":"he-IL","text":"Israeli New Sheqel","code":"ILS","exchange":".5"},
{"locale":"sc-IT","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"en-JM","text":"Jamaican Dollar","code":"JMD","exchange":"2"},
{"locale":"ja-JP","text":"Japanese Yen","code":"JPY","exchange":"2"},
{"locale":"en-JE","text":"Pound Sterling","code":"GBP","exchange":"0"},
{"locale":"ar-JO","text":"Jordanian Dinar","code":"JOD","exchange":"0"},
{"locale":"kk-KZ","text":"Kazakhstani Tenge","code":"KZT","exchange":"2.5"},
{"locale":"ki-KE","text":"Kenyan Shilling","code":"KES","exchange":"2"},
{"locale":"en-KI","text":"Australian Dollar","code":"AUD","exchange":"0"},
{"locale":"ko-KP","text":"DPRK Won","code":"KPW","exchange":"3"},
{"locale":"ko-KR","text":"Korean Won","code":"KRW","exchange":"3"},
{"locale":"ar-KW","text":"Kuwaiti Dinar","code":"KWD","exchange":"-.5"},
{"locale":"ky-KG","text":"Kyrgyz Som","code":"KGS","exchange":"2"},
{"locale":"lo-LA","text":"Lao Kip","code":"LAK","exchange":"3"},
{"locale":"lv-LV","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"ar-LB","text":"Lebanese Pound","code":"LBP","exchange":"3"},
{"locale":"st-LS","text":"Lesotho Loti","code":"LSL","exchange":"1"},
{"locale":"ff-LR","text":"Liberian Dollar","code":"LRD","exchange":"2"},
{"locale":"ar-LY","text":"Libyan Dinar","code":"LYD","exchange":".5"},
{"locale":"gsw-LI","text":"Swiss Franc","code":"CHF","exchange":"0"},
{"locale":"lt-LT","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"lb-LU","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"pt-MO","text":"Macanese Pataca","code":"MOP","exchange":"1"},
{"locale":"mk-MK","text":"North Macedonian Denar","code":"MKD","exchange":"1.5"},
{"locale":"mg-MG","text":"Malagasy Ariary","code":"MGA","exchange":"3.5"},
{"locale":"en-MW","text":"Malawian Kwacha","code":"MWK","exchange":"3"},
{"locale":"ms-MY","text":"Malaysian Ringgit","code":"MYR","exchange":".5"},
{"locale":"dv-MV","text":"Maldivian Rufiyaa","code":"MVR","exchange":"1"},
{"locale":"bm-ML","text":"CFA Franc","code":"XOF","exchange":"2.5"},
{"locale":"mt-MT","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"en-MH","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"fr-MQ","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"ar-MR","text":"Mauritanian Ouguiya","code":"MRU","exchange":"1.5"},
{"locale":"mfe-MU","text":"Mauritian Rupee","code":"MUR","exchange":"1.5"},
{"locale":"fr-YT","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"es-MX","text":"Mexican Peso","code":"MXN","exchange":"1"},
{"locale":"en-FM","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"ro-MD","text":"Moldovan Leu","code":"MDL","exchange":"1"},
{"locale":"fr-MC","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"mn-MN","text":"Mongolian Tugrik","code":"MNT","exchange":"3.5"},
{"locale":"sr-ME","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"en-MS","text":"East Caribbean Dollar","code":"XCD","exchange":".5"},
{"locale":"ar-MA","text":"Moroccan Dirham","code":"MAD","exchange":"1"},
{"locale":"pt-MZ","text":"Mozambican Metical","code":"MZN","exchange":"2"},
{"locale":"my-MM","text":"Myanmar Kyat","code":"MMK","exchange":"3"},
{"locale":"en-NA","text":"Namibian Dollar","code":"NAD","exchange":"1"},
{"locale":"en-NR","text":"Australian Dollar","code":"AUD","exchange":"0"},
{"locale":"ne-NP","text":"Nepalese Rupee","code":"NPR","exchange":"2"},
{"locale":"nl-NL","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"fr-NC","text":"CFP Franc","code":"XPF","exchange":"2"},
{"locale":"mi-NZ","text":"New Zealand Dollar","code":"NZD","exchange":"0"},
{"locale":"es-NI","text":"Nicaraguan Córdoba","code":"NIO","exchange":"1.5"},
{"locale":"ha-NE","text":"CFA Franc","code":"XOF","exchange":"2.5"},
{"locale":"en-NG","text":"Nigeria Naira","code":"NGN","exchange":"2.5"},
{"locale":"en-NU","text":"New Zealand Dollar","code":"NZD","exchange":"0"},
{"locale":"en-NF","text":"Australian Dollar","code":"AUD","exchange":"0"},
{"locale":"en-MP","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"nb-NO","text":"Norwegian Krone","code":"NOK","exchange":"1"},
{"locale":"ar-OM","text":"Omani Rial","code":"OMR","exchange":"-.5"},
{"locale":"ur-PK","text":"Pakistani Rupee","code":"PKR","exchange":"2"},
{"locale":"en-PW","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"es-PA","text":"Panamanian Balboa","code":"PAB","exchange":"0"},
{"locale":"en-PG","text":"Papua New Guinean Kina","code":"PGK","exchange":".5"},
{"locale":"gn-PY","text":"Paraguayan Guarani","code":"PYG","exchange":"3.5"},
{"locale":"es-PE","text":"Peruvian Sol","code":"PEN","exchange":".5"},
{"locale":"fil-PH","text":"Philippine Peso","code":"PHP","exchange":"1.5"},
{"locale":"en-PN","text":"New Zealand Dollar","code":"NZD","exchange":"0"},
{"locale":"pl-PL","text":"Polish Złoty","code":"PLN","exchange":".5"},
{"locale":"pt-PT","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"es-PR","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"ar-QA","text":"Qatari Rial","code":"QAR","exchange":".5"},
{"locale":"fr-RE","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"ro-RO","text":"Romanian Leu","code":"RON","exchange":".5"},
{"locale":"ru-RU","text":"Russian Ruble","code":"RUB","exchange":"2"},
{"locale":"rw-RW","text":"Rwandan Franc","code":"RWF","exchange":"3"},
{"locale":"fr-BL","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"en-SH","text":"Saint Helena Pound","code":"SHP","exchange":"0"},
{"locale":"en-KN","text":"East Caribbean Dollar","code":"XCD","exchange":".5"},
{"locale":"en-LC","text":"East Caribbean Dollar","code":"XCD","exchange":".5"},
{"locale":"fr-MF","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"fr-PM","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"en-VC","text":"East Caribbean Dollar","code":"XCD","exchange":".5"},
{"locale":"sm-WS","text":"Samoan Tala","code":"WST","exchange":"0"},
{"locale":"it-SM","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"pt-ST","text":"São Toméan Dobra","code":"STN","exchange":"1"},
{"locale":"ar-SA","text":"Saudi Riyal","code":"SAR","exchange":".5"},
{"locale":"wo-SN","text":"CFA Franc","code":"XOF","exchange":"2.5"},
{"locale":"sr-RS","text":"Serbian Dinar","code":"RSD","exchange":"2"},
{"locale":"fr-SC","text":"Seychellois Rupee","code":"SCR","exchange":"1"},
{"locale":"ff-SL","text":"Sierra Leonean Leone","code":"SLL","exchange":"4"},
{"locale":"ms-SG","text":"Singapore Dollar","code":"SGD","exchange":"0"},
{"locale":"nl-SX","text":"Netherlands Antillean Guilder","code":"ANG","exchange":"0"},
{"locale":"sk-SK","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"sl-SI","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"en-SB","text":"Solomon Islands Dollar","code":"SBD","exchange":"1"},
{"locale":"so-SO","text":"Somali Shilling","code":"SOS","exchange":"2.5"},
{"locale":"en-ZA","text":"South African Rand","code":"ZAR","exchange":"1"},
{"locale":"nus-SS","text":"South Sudanese Pound","code":"SSP","exchange":"2"},
{"locale":"eu-ES","text":"Euro","code":"EUR","exchange":"0"},
{"locale":"si-LK","text":"Sri Lanka Rupee","code":"LKR","exchange":"2"},
{"locale":"ar-SD","text":"Sudanese Pound","code":"SDG","exchange":"2.5"},
{"locale":"nl-SR","text":"Surinamese Dollar","code":"SRD","exchange":"1"},
{"locale":"nb-SJ","text":"Norwegian Krone","code":"NOK","exchange":"1"},
{"locale":"sv-SE","text":"Swedish Krona","code":"SEK","exchange":"1"},
{"locale":"rm-CH","text":"Swiss Franc","code":"CHF","exchange":"0"},
{"locale":"ar-SY","text":"Syrian Pound","code":"SYP","exchange":"3.5"},
{"locale":"zh-TW","text":"New Taiwan Dollar","code":"TWD","exchange":"1.5"},
{"locale":"tg-TJ","text":"Tajik Somoni","code":"TJS","exchange":"1"},
{"locale":"sw-TZ","text":"Tanzanian Shilling","code":"TZS","exchange":"3"},
{"locale":"th-TH","text":"Thai Baht","code":"THB","exchange":"1.5"},
{"locale":"pt-TL","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"ee-TG","text":"CFA Franc","code":"XOF","exchange":"2.5"},
{"locale":"en-TK","text":"New Zealand Dollar","code":"NZD","exchange":"0"},
{"locale":"to-TO","text":"Tongan Pa’anga","code":"TOP","exchange":"0"},
{"locale":"en-TT","text":"Trinidad and Tobago Dollar","code":"TTD","exchange":"1"},
{"locale":"ar-TN","text":"Tunisian Dinar","code":"TND","exchange":"0"},
{"locale":"tr-TR","text":"Turkish Lira","code":"TRY","exchange":"1"},
{"locale":"tk-TM","text":"Turkmen New Manat","code":"TMT","exchange":".5"},
{"locale":"en-TC","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"en-TV","text":"Australian Dollar","code":"AUD","exchange":"0"},
{"locale":"en-UG","text":"Uganda Shilling","code":"UGX","exchange":"3.5"},
{"locale":"uk-UA","text":"Ukrainian Hryvnia","code":"UAH","exchange":"1"},
{"locale":"ar-AE","text":"UAE Dirham","code":"AED","exchange":".5"},
{"locale":"cy-GB","text":"Pound Sterling","code":"GBP","exchange":"0"},
{"locale":"chr-US","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"es-UY","text":"Uruguayan Peso","code":"UYU","exchange":"1.5"},
{"locale":"uz-UZ","text":"Uzbek Soʻm","code":"UZS","exchange":"4"},
{"locale":"en-VU","text":"Ni-Vanuatu Vatu","code":"VUV","exchange":"2"},
{"locale":"es-VE","text":"Venezuelan Bolívar Soberano","code":"VES","exchange":"6.5"},
{"locale":"vi-VN","text":"Vietnamese Dong","code":"VND","exchange":"4"},
{"locale":"en-VG","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"en-VI","text":"US Dollar","code":"USD","exchange":"0"},
{"locale":"fr-WF","text":"CFP Franc","code":"XPF","exchange":"2"},
{"locale":"ar-EH","text":"Moroccan Dirham","code":"MAD","exchange":"1"},
{"locale":"ar-YE","text":"Yemeni Rial","code":"YER","exchange":"2"},
{"locale":"en-ZM","text":"Zambian Kwacha","code":"ZMW","exchange":"1"},
{"locale":"en-ZW","text":"Zimbabwe Dollar","code":"ZWL","exchange":"2.5"}
];